<a href="https://colab.research.google.com/github/Gurirath/VIT---EDA---Projects---Classwork--25BAI0153/blob/main/Labwork_4_8_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Discretization and Binning

In [14]:
import pandas as pd
height = [120, 122, 125, 127, 121, 123, 137, 131, 161, 145, 141, 132]
bins = [118, 125, 135, 160, 200]
category = pd.cut(height, bins)
display(category)

[(118, 125], (118, 125], (118, 125], (125, 135], (118, 125], ..., (125, 135], (160, 200], (135, 160], (135, 160], (125, 135]]
Length: 12
Categories (4, interval[int64, right]): [(118, 125] < (125, 135] < (135, 160] < (160, 200]]

From the above output:
- A parenthesis indicates that the side is open.
- A square bracket means that it is closed or inclusive.

From the preceding code block, `(118, 125]` means the left-hand side is open and the right-hand side is closed. This is mathematically denoted as follows:

`(a,b] = {a | a < x ≤ b}`

Hence, 118 is not included, but anything greater than 118 is included, while 125 is included in the interval.

We can check the number of values in each bin by using the `pd.value_counts()` method (using `pd.Series(obj).value_counts()` as recommended).

In [15]:
display(pd.Series(category).value_counts())

(118, 125]    5
(125, 135]    3
(135, 160]    3
(160, 200]    1
Name: count, dtype: int64

In [16]:
bin_names = ['Short Height', 'Average height', 'Good Height', 'Taller']
display(pd.cut(height, bins, labels=bin_names))

['Short Height', 'Short Height', 'Short Height', 'Average height', 'Short Height', ..., 'Average height', 'Taller', 'Good Height', 'Good Height', 'Average height']
Length: 12
Categories (4, object): ['Short Height' < 'Average height' < 'Good Height' < 'Taller']

In [17]:
import numpy as np
display(pd.cut(np.random.rand(40), 5, precision=2))

[(0.62, 0.81], (0.26, 0.44], (0.44, 0.62], (0.26, 0.44], (0.077, 0.26], ..., (0.077, 0.26], (0.26, 0.44], (0.81, 0.99], (0.077, 0.26], (0.26, 0.44]]
Length: 40
Categories (5, interval[float64, right]): [(0.077, 0.26] < (0.26, 0.44] < (0.44, 0.62] <
                                           (0.62, 0.81] < (0.81, 0.99]]

## Quantile-based Binning (`qcut`)

In [18]:
randomNumbers = np.random.rand(2000)
category3 = pd.qcut(randomNumbers, 4)
display(category3)

[(0.482, 0.726], (0.482, 0.726], (0.482, 0.726], (0.482, 0.726], (0.233, 0.482], ..., (0.0005499999999999999, 0.233], (0.0005499999999999999, 0.233], (0.233, 0.482], (0.233, 0.482], (0.726, 0.998]]
Length: 2000
Categories (4, interval[float64, right]): [(0.0005499999999999999, 0.233] < (0.233, 0.482] < (0.482, 0.726] <
                                           (0.726, 0.998]]

In [19]:
display(pd.Series(category3).value_counts())

(0.0005499999999999999, 0.233]    500
(0.233, 0.482]                    500
(0.482, 0.726]                    500
(0.726, 0.998]                    500
Name: count, dtype: int64

## Outlier Detection and Filtering

- Outliers are data points that diverge from other observations for several reasons.
- During the EDA phase, one of our common tasks is to detect and filter these outliers.
- The main reason for this detection and filtering of outliers is that the presence of such outliers can cause serious issues in statistical analysis.

In [20]:
df = pd.read_csv('https://raw.githubusercontent.com/salemprakash/EDA/main/Data/sales.csv')
display(df.head(10))

,Account,Company,Order,SKU,Country,Year,Quantity,UnitPrice,transactionComplete
0,123456779,Kulas Inc,99985,s9-supercomputer,Aruba,1981,5148,545,False
1,123456784,GitHub,99986,s4-supercomputer,Brazil,2001,3262,383,False
2,123456782,Kulas Inc,99990,s10-supercomputer,Montserrat,1973,9119,407,True
3,123456783,My SQ Man,99999,s1-supercomputer,El Salvador,2015,3097,615,False
4,123456787,ABC Dogma,99996,s6-supercomputer,Poland,1970,3356,91,True
5,123456778,Super Sexy Dingo,99996,s9-supercomputer,Costa Rica,2004,2474,136,True
6,123456783,ABC Dogma,99981,s11-supercomputer,Spain,2006,4081,195,False
7,123456785,ABC Dogma,99998,s9-supercomputer,Belarus,2015,6576,603,False
8,123456778,Loolo INC,99997,s8-supercomputer,Mauritius,1999,2460,36,False
9,123456775,Kulas Inc,99997,s7-supercomputer,French Guiana,2004,1831,664,True

In [21]:
df['TotalPrice'] = df['UnitPrice'] * df['Quantity']
display(df)

,Account,Company,Order,SKU,Country,Year,Quantity,UnitPrice,transactionComplete,TotalPrice
0,123456779,Kulas Inc,99985,s9-supercomputer,Aruba,1981,5148,545,False,2805660
1,123456784,GitHub,99986,s4-supercomputer,Brazil,2001,3262,383,False,1249346
2,123456782,Kulas Inc,99990,s10-supercomputer,Montserrat,1973,9119,407,True,3711433
3,123456783,My SQ Man,99999,s1-supercomputer,El Salvador,2015,3097,615,False,1904655
4,123456787,ABC Dogma,99996,s6-supercomputer,Poland,1970,3356,91,True,305396
...,...,...,...,...,...,...,...,...,...,...
9995,123456784,Pryianka Ji,99987,s1-supercomputer,Jamaica,1983,886,475,False,420850
9996,123456775,Will LLC,99985,s3-supercomputer,Vietnam,2002,9995,302,True,3018490
9997,123456774,Kulas Inc,99982,s2-supercomputer,Northern Mariana Islands,1979,1421,249,True,353829
9998,123456781,Loolo INC,99986,s5-supercomputer,Mali,1991,2342,506,False,1185052
9999,123456775,Super Sexy Dingo,99987,s1-supercomputer,Luxembourg,1982,5282,222,False,1172604

In [22]:
TotalTransaction = df["TotalPrice"]
display(TotalTransaction[np.abs(TotalTransaction) > 3000000])

2       3711433
7       3965328
13      4758900
15      5189372
17      3989325
         ...
9977    3475824
9984    5251134
9987    5670420
9991    5735513
9996    3018490
Name: TotalPrice, Length: 2094, dtype: int64

In [23]:
display(df[np.abs(TotalTransaction) > 6741112])

,Account,Company,Order,SKU,Country,Year,Quantity,UnitPrice,transactionComplete,TotalPrice
818,123456781,Gen Power,99991,s1-supercomputer,Burkina Faso,1985,9693,696,False,6746328
1402,123456778,Will LLC,99985,s11-supercomputer,Austria,1990,9844,695,True,6841580
2242,123456770,Name IT,99997,s9-supercomputer,Myanmar,1979,9804,692,False,6784368
2876,123456772,Gen Power,99992,s10-supercomputer,Mali,2007,9935,679,False,6745865
3210,123456782,Loolo INC,99991,s8-supercomputer,Kuwait,2006,9886,692,False,6841112
3629,123456779,My SQ Man,99980,s3-supercomputer,Hong Kong,1994,9694,700,False,6785800
7674,123456781,Loolo INC,99989,s6-supercomputer,Sri Lanka,1994,9882,691,False,6828462
8645,123456789,Gen Power,99996,s11-supercomputer,Suriname,2005,9742,699,False,6809658
8684,123456785,Gen Power,99989,s2-supercomputer,Kenya,2013,9805,694,False,6804670

## Feature Scaling and Normalization

In [24]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
data = {
 'Age': [25, 30, 45, 35, 22],
 'Salary': [50000, 64000, 120000, 85000, 1200000]
}
df = pd.DataFrame(data)
print("Original Data:\n", df, "\n")

Original Data:
    Age   Salary
0   25    50000
1   30    64000
2   45   120000
3   35    85000
4   22  1200000

In [25]:
min_max_scaler = MinMaxScaler()
df_min_max = pd.DataFrame(
 min_max_scaler.fit_transform(df),
 columns=df.columns
)
print("Min-Max Scaled Data:\n", df_min_max, "\n")

Min-Max Scaled Data:
         Age    Salary
0  0.130435  0.000000
1  0.347826  0.012174
2  1.000000  0.060870
3  0.565217  0.030435
4  0.000000  1.000000

In [26]:
standard_scaler = StandardScaler()
df_standard = pd.DataFrame(
 standard_scaler.fit_transform(df),
 columns=df.columns
)
print("Standardized Data:\n", df_standard, "\n")

Standardized Data:
         Age    Salary
0 -0.788742 -0.565609
1 -0.172537 -0.534409
2  1.676077 -0.409609
3  0.443667 -0.487609
4 -1.158465  1.997236